In [1]:
import numpy as np

In [2]:
list1 = [111,222,333]

In [3]:
type(list1)

list

In [9]:
arr1 = np.array(list1)  ### convert list to array
type(arr1)

numpy.ndarray

In [6]:
np.arange(0,20)  ##creates the sequence of number

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
np.arange(0,20,3)  ##creates sequence with seapration of 3

array([ 0,  3,  6,  9, 12, 15, 18])

In [11]:
np.zeros(4)  ## array of four zeroes


array([0., 0., 0., 0.])

In [13]:
np.zeros((2,2)) ## 2x2 matrix with zeroes

array([[0., 0.],
       [0., 0.]])

In [14]:
np.ones((3,3)) ## 3x3 matrix with ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
num1 = np.linspace(1,10, 100) ##linear spacing of 100 between 1 to 10

In [16]:
num1

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [17]:
array3 = np.eye(3)  ##identity matrix

In [19]:
array3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.random.randint(1,50, 5)  ##5 random values between 1 to 50

array([14, 29, 37,  3, 26])

In [29]:
#################
ar1 = np.array([23,7,3,14,5,66,2,8,9])
print(ar1)

[23  7  3 14  5 66  2  8  9]


In [42]:
ar1 = ar1.reshape(3,3)  ###### reshape in form of  rows and columns

In [43]:
ar1.shape  ### dimension of array

(3, 3)

In [45]:
ar1.max()  ## max value

66

In [46]:
ar1.min()  ## min value

2

In [48]:
ar1.argmax()  ##  position of max

5

In [50]:
ar1.argmin() ##  position of min

6

In [51]:
import pandas as pd

cr= pd.read_csv(r"C:\Users\Khushi\Downloads\CreditRisk.csv")

In [54]:
np.unique(cr.Property_Area)  ## Unique values

array(['Rural', 'Semiurban', 'Urban'], dtype=object)

In [57]:
np.mean(cr.LoanAmount)
np.std(cr.LoanAmount)

77.38115506022456

In [58]:
np.max(cr.Loan_Amount_Term)

480.0

In [60]:
import math

In [68]:
math.factorial(6)

720

In [69]:
math.sinh(90)

6.102016471589204e+38

In [70]:
math.fabs(-5)

5.0

In [73]:
math.floor(4.9)
math.ceil(4.4)

5

In [76]:
math.fmod(77,12)

5.0

In [77]:
math.exp(5)

148.4131591025766

In [79]:
math.log10(100)

2.0

In [80]:
math.log(100,10)

2.0

In [82]:
math.log(27,3)

3.0

In [92]:
math.cos(math.radians(90))

6.123233995736766e-17

In [89]:
math.sqrt(1200)

34.64101615137755

In [93]:
math.e

2.718281828459045

In [94]:
math.pi

3.141592653589793